import argparse
import itertools
import json
import re
import time
import typing
from pathlib import Path

import bs4
import requests
import yt_dlp
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager


# TODO: auto load cookies from browser files
# Load cookies into the browser
def load_cookies(driver, file_path: str):
    cookies = json.loads(Path(file_path).read_text())
    for cookie in cookies:
        driver.add_cookie(
            {
                "name": cookie["name"],
                "value": cookie["value"],
                "domain": cookie["domain"],
            }
        )


# TODO: figure out how to convert json cookies to netscape cookies
def json_to_netscape(json_file):
    """
    Converts a JSON cookies file to Netscape format.

    :param json_file: Path to the input JSON cookies file.
    """
    # Get the base name and change the extension to .txt
    json_path = Path(json_file)
    netscape_file = json_path.with_suffix(".txt")

    if netscape_file.exists():
        print("Netscape cookies found.")
        return netscape_file

    try:
        with open(json_file, "r") as file:
            cookies = json.load(file)

        with open(netscape_file, "w") as file:
            # Write the netscape header
            file.write("# Netscape HTTP Cookie File\n")
            file.write("# This file is generated by a script\n\n")

            for cookie in cookies:
                # Extract fields
                domain: str = cookie.get("domain", "")
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path: str = cookie.get("path", "/")
                secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                expiry = int(cookie.get("expirationDate", "0"))
                name: str = cookie.get("name", "")
                value = cookie.get("value", "")

                # Write to Netscape format
                file.write(
                    f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n"
                )

        return netscape_file
    except Exception as e:
        print(f"Error converting cookies: {e}")


# Fetch the TikTok page
def fetch_page(url: str, file_path: str):
    options = Options()
    # options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("start-maximized")
    options.add_argument("enable-automation")
    options.add_argument("--disable-blink-features=AutomationControlled")

    # Set up WebDriver Manager
    driver = webdriver.Chrome(
        options=options, service=ChromeService()
    )
    driver.get("https://www.tiktok.com/")

    # Load cookies
    load_cookies(driver, file_path)
    driver.refresh()

    # Navigate to the target URL
    driver.get(url)

    try:
        # Wait for the page to load completely
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located(
                (By.CSS_SELECTOR, ".css-18ie8zf-PFavorite")
            )
        )

        # go to favorites
        clickable = driver.find_element(By.CSS_SELECTOR, ".css-18ie8zf-PFavorite");
        clickable.click()
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located(
                (By.ID, "collections")
            )
        )

        # get collections
        clickable = driver.find_element(By.ID, "collections");
        clickable.click()

        # load all collections
        SCROLL_PAUSE_TIME = 1.0

        # Get scroll height
        last_height = driver.execute_script("return document.body.scrollHeight")

        while True:
            # Scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

            # Wait to load page
            time.sleep(SCROLL_PAUSE_TIME)

            # Calculate new scroll height and compare with last scroll height
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height

        # time.sleep(100000)
        return driver.page_source
    except Exception as e:
        print(f"Failed to fetch the page: {e}")
        return None
    finally:
        driver.quit()

def parse_collections(html):
    # collection div class css-13fa1gi-DivWrapper
    # class link-a11y-focus, get href
    # get picture/img
    # alt is collection name, src is pic
    soup = bs4.BeautifulSoup(html, "html.parser")
    collection_tags = soup.select(".css-13fa1gi-DivWrapper")
    collections=[]
    for collection in collection_tags:
        anchor = typing.cast(typing.Optional[bs4.element.Tag],collection.find("a", "link-a11y-focus"))
        if anchor is None:
            raise RuntimeError("Collection div with URL does not exist")

        href = typing.cast(str,anchor["href"])
        url = "https://tiktok.com" + href

        image = typing.cast(typing.Optional[bs4.element.Tag],anchor.find("img"))
        if image is None:
            raise RuntimeError("Collection image is missing, name cannot be determined")

        name = image["alt"]
        image_url = image["src"]

        collection_dict = {
            "name": name,
            "image": image_url,
            "url": url
        }
        collections += [collection_dict]

    return collections


def main():
    # Parse command-line args
    parser = argparse.ArgumentParser(description="Download TikTok slideshow images.")
    parser.add_argument("link", help="TikTok video link")
    parser.add_argument(
        "--cookies", required=True, help="Path to the cookies file (cookies.json)"
    )
    parser.add_argument(
        "--output", required=True, help="Output "
    )
    args = parser.parse_args()

    html = fetch_page(args.link, args.cookies)
    collections = parse_collections(html)
    print(collections)
    print(len(collections))


if __name__ == "__main__":
    main()
