import json
import random
import re
import requests
import sqlite3
from pathlib import Path

from tikapi import TikAPI, ValidationException, ResponseException

MAX_ATTEMPTS=2
base_dir="/ZFS/ZFS-primary/backups/tiktok-backups"
# base_dir="/home/alice/Scripts/tiktok-backup/"
video_dir="raw-videos"
user_dir="user-details"
database_path=f"{base_dir}/{video_dir}/index.db"
image_regex=re.compile(r"\/([^\/]*\.(?:jpeg|png|jpg|image))")

def extract_users(username):
    api_key=None
    with open("./tikapi.key","r") as f:
        api_key=f.read()
    print(f"extracting {username}")
    api = TikAPI(api_key)
    try:
        response = api.public.check(
            username=username
        )

        return response.json()

    except ValidationException as e:
        print(e, e.field)

    except ResponseException as e:
        if int(e.response.status_code) == 429:
            exit(1)
        print(e, e.response.status_code)

def update_user_details_table(userid,username):
    print(f"updating user detail ts for {username}")
    con =  sqlite3.connect(database_path,timeout = 500)
    user_query="insert into userdetailtable(userid,username,lastupdatedts) values (?,?,unixepoch('now')) on conflict(userid) do update set lastupdatedts=unixepoch('now')"
    con.execute(user_query,(userid,username))
    con.commit()
    con.close()


# TODO: auto load cookies from browser files
# Load cookies into the browser
def load_cookies(driver, file_path: str):
    cookies = json.loads(Path(file_path).read_text())
    for cookie in cookies:
        driver.add_cookie(
            {
                "name": cookie["name"],
                "value": cookie["value"],
                "domain": cookie["domain"],
            }
        )


# TODO: figure out how to convert json cookies to netscape cookies
def json_to_netscape(json_file):
    """
    Converts a JSON cookies file to Netscape format.

    :param json_file: Path to the input JSON cookies file.
    """
    # Get the base name and change the extension to .txt
    json_path = Path(json_file)
    netscape_file = json_path.with_suffix(".txt")

    if netscape_file.exists():
        print("Netscape cookies found.")
        return netscape_file

    try:
        with open(json_file, "r") as file:
            cookies = json.load(file)

        with open(netscape_file, "w") as file:
            # Write the netscape header
            file.write("# Netscape HTTP Cookie File\n")
            file.write("# This file is generated by a script\n\n")

            for cookie in cookies:
                # Extract fields
                domain: str = cookie.get("domain", "")
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path: str = cookie.get("path", "/")
                secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                expiry = int(cookie.get("expirationDate", "0"))
                name: str = cookie.get("name", "")
                value = cookie.get("value", "")

                # Write to Netscape format
                file.write(
                    f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n"
                )

        return netscape_file
    except Exception as e:
        print(f"Error converting cookies: {e}")

def fetch_users():
    print("fetching un-checked users")
    con =  sqlite3.connect(database_path,timeout = 500)
    user_query="SELECT t1.userid, t1.username FROM usertable t1 LEFT JOIN userdetailtable t2 ON t2.userid = t1.userid WHERE t2.userid IS null"
    res = con.execute(user_query)
    users = res.fetchall()
    con.close()
    return users

def fetch_image(path,image_url):
    print(f"fetching image {path}")
    img_data = requests.get(image_url).content
    with open(path, 'wb') as handler:
        handler.write(img_data)

def main():

    users = fetch_users()
    for (userid, username) in users:
        print(userid,username)

        user_data = extract_users(username)
        if user_data is None:
            continue
        user_path=f"{base_dir}/{user_dir}/{userid}"
        Path(user_path).mkdir(exist_ok=True)

        with open(f"{user_path}/info.json", 'w', encoding='utf-8') as f:
            json.dump(user_data, f, ensure_ascii=False, indent=4)
        avatar_larger_url=user_data["userInfo"]["user"]["avatarLarger"]
        avatar_medium_url=user_data["userInfo"]["user"]["avatarMedium"]
        avatar_thumb_url=user_data["userInfo"]["user"]["avatarThumb"]

        avatar_larger_name=image_regex.search(avatar_larger_url)
        avatar_medium_name=image_regex.search(avatar_medium_url)
        avatar_thumb_name=image_regex.search(avatar_thumb_url)

        avatar_larger_name = avatar_larger_name.group(1) if avatar_larger_name is not None else "profile_large.image"
        avatar_medium_name = avatar_medium_name.group(1) if avatar_medium_name is not None else "profile_medium.image"
        avatar_thumb_name = avatar_thumb_name.group(1) if avatar_thumb_name is not None else "profile_thumb.image"

        fetch_image(f"{user_path}/{avatar_larger_name}",avatar_larger_url)
        fetch_image(f"{user_path}/{avatar_medium_name}",avatar_medium_url)
        fetch_image(f"{user_path}/{avatar_thumb_name}",avatar_thumb_url)
        update_user_details_table(userid,username)


if __name__ == "__main__":
    main()
