import json
import sqlite3
from pathlib import Path

from tikapi import TikAPI, ValidationException, ResponseException

MAX_ATTEMPTS=2
base_dir="/ZFS/ZFS-primary/backups/tiktok-backups"
video_dir="raw-videos"
user_dir="user-details"
database_path=f"{base_dir}/{video_dir}/index.db"


def extract_users(username):
    api_key = 'ZabNce77y54F66CRzTauFRvndXviTEcLbaOj0ofMUtnxiDwx'
    api = TikAPI(api_key)
    try:
        response = api.public.check(
            username=username
        )

        return response.json()

    except ValidationException as e:
        print(e, e.field)

    except ResponseException as e:
        print(e, e.response.status_code)



# TODO: auto load cookies from browser files
# Load cookies into the browser
def load_cookies(driver, file_path: str):
    cookies = json.loads(Path(file_path).read_text())
    for cookie in cookies:
        driver.add_cookie(
            {
                "name": cookie["name"],
                "value": cookie["value"],
                "domain": cookie["domain"],
            }
        )


# TODO: figure out how to convert json cookies to netscape cookies
def json_to_netscape(json_file):
    """
    Converts a JSON cookies file to Netscape format.

    :param json_file: Path to the input JSON cookies file.
    """
    # Get the base name and change the extension to .txt
    json_path = Path(json_file)
    netscape_file = json_path.with_suffix(".txt")

    if netscape_file.exists():
        print("Netscape cookies found.")
        return netscape_file

    try:
        with open(json_file, "r") as file:
            cookies = json.load(file)

        with open(netscape_file, "w") as file:
            # Write the netscape header
            file.write("# Netscape HTTP Cookie File\n")
            file.write("# This file is generated by a script\n\n")

            for cookie in cookies:
                # Extract fields
                domain: str = cookie.get("domain", "")
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path: str = cookie.get("path", "/")
                secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                expiry = int(cookie.get("expirationDate", "0"))
                name: str = cookie.get("name", "")
                value = cookie.get("value", "")

                # Write to Netscape format
                file.write(
                    f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n"
                )

        return netscape_file
    except Exception as e:
        print(f"Error converting cookies: {e}")

def fetch_users():
    con =  sqlite3.connect(database_path,timeout = 500)
    res = con.execute("select * from usertable;")
    users = res.fetchall()
    return users

def main():

    users = fetch_users()
    for (userid, username) in users:
        user_data = extract_users(username)
        user_path=f"{base_dir}/{user_dir}/{userid}"
        Path(user_path).mkdir(exist_ok=True)

        print(userid,username)
        with open(f"{user_path}/info.json", 'w', encoding='utf-8') as f:
            json.dump(user_data, f, ensure_ascii=False, indent=4)


if __name__ == "__main__":
    main()
