import argparse
import json
import random
import time
import typing
from pathlib import Path

import bs4
from fake_useragent import UserAgent
from ruamel.yaml import YAML
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager
from tiktok_captcha_solver import SeleniumSolver
import undetected_chromedriver as uc
from shutil import which


# TODO: auto load cookies from browser files
# Load cookies into the browser
def load_cookies(driver, file_path: str):
    cookies = json.loads(Path(file_path).read_text())
    for cookie in cookies:
        driver.add_cookie(
            {
                "name": cookie["name"],
                "value": cookie["value"],
                "domain": cookie["domain"],
            }
        )


# TODO: figure out how to convert json cookies to netscape cookies
def json_to_netscape(json_file):
    """
    Converts a JSON cookies file to Netscape format.

    :param json_file: Path to the input JSON cookies file.
    """
    # Get the base name and change the extension to .txt
    json_path = Path(json_file)
    netscape_file = json_path.with_suffix(".txt")

    if netscape_file.exists():
        print("Netscape cookies found.")
        return netscape_file

    try:
        with open(json_file, "r") as file:
            cookies = json.load(file)

        with open(netscape_file, "w") as file:
            # Write the netscape header
            file.write("# Netscape HTTP Cookie File\n")
            file.write("# This file is generated by a script\n\n")

            for cookie in cookies:
                # Extract fields
                domain: str = cookie.get("domain", "")
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path: str = cookie.get("path", "/")
                secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                expiry = int(cookie.get("expirationDate", "0"))
                name: str = cookie.get("name", "")
                value = cookie.get("value", "")

                # Write to Netscape format
                file.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

        return netscape_file
    except Exception as e:
        print(f"Error converting cookies: {e}")


# Fetch the TikTok page
def fetch_page(url: str, file_path: str):
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("start-maximized")
    options.add_argument("enable-automation")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--window-size=1920x1080")
    options.add_argument(f"user-agent={UserAgent(platforms='desktop').chrome}")

    uc_driver = which("undetected-chromedriver")
    browser_path = which("chromium")
    # Set up WebDriver Manager
    driver = uc.Chrome(
        driver_executable_path=uc_driver, browser_executable_path=browser_path
    )  # options=options, service=ChromeService())
    driver.get("https://www.tiktok.com/")
    driver.set_window_size(1920, 1080)

    # Load cookies
    load_cookies(driver, file_path)
    driver.refresh()

    api_key = ""

    with open("sadcaptcha.key") as f:
        api_key = f.read()

    sadcaptcha = SeleniumSolver(
        driver,
        api_key,
        mouse_step_size=1,  # Adjust to change mouse speed
        mouse_step_delay_ms=10,  # Adjust to change mouse speed
    )

    # Navigate to the target URL
    driver.get(url)
    sadcaptcha.solve_captcha_if_present()

    try:
        WebDriverWait(driver, 10).until(
            EC.visibility_of_element_located((By.CSS_SELECTOR, "[data-e2e='following']"))
        )

        # go to favorites
        clickable = driver.find_element(By.CSS_SELECTOR, "[data-e2e='following']")
        clickable.click()
        # load all collections
        SCROLL_PAUSE_TIME = 2.0

        collection_count = int(
            driver.find_element(By.CSS_SELECTOR, "[data-e2e='following-count']").text
        )
        print(f"expecting {collection_count} followers")

        WebDriverWait(driver, 30).until(
            EC.visibility_of_element_located((By.CLASS_NAME, "es616eb8"))
        )

        # get initial following
        elements = driver.find_elements(By.CLASS_NAME, "es616eb8")

        print(f"starting with {len(elements)} following")
        retries = 0
        batch_count = 30

        while True:
            for element in elements[-batch_count:]:
                driver.execute_script("arguments[0].scrollIntoView();", element)
                time.sleep(SCROLL_PAUSE_TIME / (batch_count**0.5) * random.random())

            # Wait to load page
            time.sleep(SCROLL_PAUSE_TIME)

            new_elements = driver.find_elements(By.CLASS_NAME, "es616eb8")

            elem_set = set(new_elements)
            if set(elements) == elem_set:
                if retries == 3 or len(elem_set) == collection_count:
                    print(f"found {len(elem_set)} followers")
                    break
                retries += 1
            else:
                retries = 0

            if len(elements) < len(new_elements):
                elements = new_elements
            print(f"continuing with {len(elements)} following found")

        return driver.page_source
    except Exception as e:
        print(f"Failed to fetch the page: {e}")
        print(driver.page_source)
        return None
    finally:
        driver.quit()


def parse_following(html):
    # collection div class css-13fa1gi-DivWrapper
    # class link-a11y-focus, get href
    # get picture/img
    # alt is collection name, src is pic
    soup = bs4.BeautifulSoup(html, "html.parser")
    following = soup.find_all("p", class_="es616eb8")
    following = [i.text + "\n" for i in following]

    return following


def export_following(following, out_file):
    with open(out_file, "w") as f:
        f.writelines(following)


def main():
    # Parse command-line args
    parser = argparse.ArgumentParser(description="Download TikTok slideshow images.")
    parser.add_argument("link", help="TikTok video link")
    parser.add_argument("--cookies", required=True, help="Path to the cookies file (cookies.json)")
    parser.add_argument(
        "--sadcaptcha-key-location", required=True, help="Path to sadcaptcha key file"
    )
    parser.add_argument("--output", required=True, help="Output to yaml file ")
    args = parser.parse_args()

    html = fetch_page(args.link, args.cookies)
    following = parse_following(html)

    export_following(following, args.output)


if __name__ == "__main__":
    main()
